version: '3'
services:
  db.postgres:
    container_name: db.postgres_flask
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DEBUG=true
      - POSTGRES_DB=bookdatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD='postgres'
    volumes:
      - ./docker-context/volume:/var/lib/postgresql
      - ./docker-context/init.sql:/docker-entrypoint-initdb.d/1-init.sql
  app.books:
    container_name: db.books_flask
    build: 
      context: .
    restart: always
    ports:
      - '5000:5000'
    environment:
      - DEBUG=true
      - POSTGRES_DB=bookdatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD='postgres'
    volumes:
      - ./docker-context/volume:/var/lib/postgresql
      - ./docker-context/init.sql:/docker-entrypoint-initdb.d/1-init.sql

#Install docker-compose
#sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

#execution perms
#sudo chmod +x /usr/local/bin/docker-compose

#ubuntu
#apt install docker-compose

#docker-compose up